---
- hosts: all
  become: yes
  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

- hosts: all
  become: yes
  tasks:
    - name: Upgrade the OS
      apt:
        upgrade: dist
